language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: LxKS2eK5t6bB8Cg0izBhD8yl+sYEmadcH3SLIZauCignenbdUUJk9mpqTxFH2581LBbEIwzaMzF2YLk+Y9dfR/Ce14pmcnmF9AlIGfO7NFf3+1s5xDJbp6FVCwrJoDt/XYpnmzINPInFjsGCweLXt8kMc9oCLGwrfm7AVogrNXQ6912sU6UlQpZ9NH2Dak4ZFH0dHQ/V8ZQtUGuyRQPA5IbYh+O1FYjtJ0Dxjv1dqUHJo8to/6is0X7hv4GPomNaimsNDe9nqx2V10jK5qQBCNZbz4dUVrVeeCPW3xMkFcFaQxwps0GnjVfDwnEbHo/1CaqyA4Y86pDmwKEbGPeQY0KIpIy/5NznzaUhKXOTAZ4XGUGbvnacDGgRTmurU9vRe92TTdFOzm93Wwf8ZY1tW3ytP+X8ElSKuCcnORxWeTzidt/Z+kUzmYNs/mfErH0wqVMsDbIEXxs2yURPjoZPtlgkPNRJzMQ5PxkwfmUjOZxmdLQQXmjUMQe6zpP7pjVPnHtesaW/sks4FHlNjNXaZ7vNXtivSsuL9YKZyMo49BZQ7GiTpiiyQ6vLAe2aW7u/Oij1zXIwPwo87XxQsC1M+0TLm48o8IV9UEER7nJQYopuM20WDqveZzWn/L5n2LsgO5hq7Nb1MMI1t+NCVcPSDP2QEBItCUc10BazJkrB1yE=
  app: morning-waters-27863
  on:
    repo: amandareilly/youquity-client
