language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: ZC3OwPgvHTq5YY8PKAq8N1N3SHKWqdPfp5lnGqlEo4PO2FqrTQpTQxlwGpXVA9YJv+wv2I7NOjbgOuxYfSoJlc5/XXTmwRJ+gZhJ1odlKexf7yXvkdv8/4zaczmKxILw6SSIkqR4fLrD2roCSkx7ha9D3CVKElz4YF8Vqck6IrOi44/F00BLNMPd9xmrcbX+W8N8MC0cdGe4QjfRGbrOka9Q90f5eyK586p+14HtgnMiwoD4RvrAAqWsXCMMYu2y+vHF/+cz/XunuxFnaP8vJ/jJFwIXyoDdpcYPPGRGUm4g7sIyTQXQWfIplCA1nHk570wc04N23H6MDTiBPQ74ZWXEGaxM6xttRVkoR2kfGKnaKRMU6lBv/7j1Y9wbZiDbPXA6Jsq/9zM/DDQ71AdadXKZHIh+4+2LxozUojq4suJF7JH1BvRYELs7spCsrenOpzPSiNLiR7dJN1nU83RYlfKvW/cY1tPzBda9g3UmMDcX9rHBJ6fWJZc6S+LpbJkxGYhZD267pQixsgBes7XP88+6/a2RF0hv4r6vu4QigK0RWmMJ00wuS1AgfJYzXTwtzpvQs0bQyPv9dYEziF/XePMA+CAj56zXGGzfICjaoIit9dUvU8+SYoteh7qq+OHNv/rpZJXeusRrYhN1NEWskPfVDlzD7a4nHXvtw2/EtxE=
  app: morning-waters-27863
  on:
    repo: amandareilly/youquity-client
